version: '3.7'
services:
  proxy:
    image: kainonly/swoole-alpine
    command: 'php bin/hyperf.php di:init-proxy'
    volumes:
      - ./:/app
  update:
    image: kainonly/composer-alpine
    command: 'composer update --prefer-dist -o --no-dev --ignore-platform-reqs'
    volumes:
      - ../.composer:/tmp
      - ./:/app